name: Create ZIP on Push (Windows)

on:
  push:
    branches:
      - main

jobs:
  create-zip:
    runs-on: windows-latest

    steps:
      # 1. Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Créer un fichier ZIP en utilisant PowerShell
      - name: Create ZIP file
        run: |
          powershell -Command "Compress-Archive -Path * -DestinationPath main.zip"

      # 3. Télécharger le fichier ZIP en tant qu'artifact
      - name: Upload ZIP file
        uses: actions/upload-artifact@v4
        with:
          name: main-branch-zip
          path: main.zip
