name: Update ZIP on Push (Windows)

on:
  push:
    branches:
      - main

jobs:
  update-zip:
    runs-on: windows-latest

    steps:
      # 1. Checkout du dépôt avec le jeton
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Supprimer l'ancien fichier ZIP s'il existe
      - name: Remove old ZIP file
        run: |
          if (Test-Path main.zip) {
            Remove-Item -Force main.zip
          }

      # 3. Créer un nouveau fichier ZIP
      - name: Create new ZIP file
        run: |
          powershell -Command "Compress-Archive -Path * -DestinationPath main.zip"

      # 4. Ajouter et committer le nouveau fichier ZIP
      - name: Commit new ZIP file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add main.zip
          git commit -m "Update main.zip with latest changes"

      # 5. Pousser les modifications dans la branche principale
      - name: Push changes
        run: |
          git push origin main
