name: Create ZIP Archive on Push (Windows)

on:
  push:
    branches:
      - main  # Remplacez par la branche que vous souhaitez suivre

jobs:
  create-archive:
    runs-on: windows-latest  # Utilisation d'un environnement Windows

    steps:
      # 1. Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Créer un fichier ZIP contenant tous les fichiers du projet
      - name: Create ZIP archive
        run: |
          Compress-Archive -Path * -DestinationPath archive.zip  # Crée l'archive sur Windows avec PowerShell

      # 3. Configurer Git pour pouvoir pousser le fichier ZIP dans le dépôt
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 4. Ajouter l'archive ZIP, faire un commit et le pousser dans le dépôt
      - name: Commit and Push ZIP file
        run: |
          git add archive.zip
          git commit -m "Add updated ZIP archive"
          git push origin main  # Pousse l'archive dans le dépôt (branche main)
